django_project/about/urls.py
__all__ = ()

import django.urls

import about.views


app_name = "about"

urlpatterns = [
    django.urls.path("", about.views.AboutView.as_view(), name="about"),
]

django_project/django_project/urls.py
__all__ = ()

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("tz_detect/", include("tz_detect.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("auth/", include("users.urls.auth_urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("users/", include("users.urls.users_urls")),
    path("tasks/", include("tasks.urls")),
    path("training/", include("training.urls")),
    path("", include("homepage.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += debug_toolbar.toolbar.debug_toolbar_urls()

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

django_project/tasks/urls.py
__all__ = ()

from django.urls import include, path

app_name = "tasks"

urlpatterns = [
    path("text/", include("tasks.routes.text")),
    path("image/", include("tasks.routes.image")),
    path("audio/", include("tasks.routes.audio")),
]

django_project/tasks/forms/audio.py
__all__ = ()

from django import forms
from django.utils.translation import gettext_lazy as _

from tasks.forms.base import BaseTaskCheckForm, BaseTaskForm
import tasks.models


class AudioTaskForm(BaseTaskForm):
    class Meta(BaseTaskForm.Meta):
        model = tasks.models.AudioTask

        audio_field = model.audio.field.name

        fields = BaseTaskForm.Meta.fields + [
            audio_field,
        ]
        widgets = {
            audio_field: forms.FileInput(
                attrs={
                    "class": "form-control",
                    "accept": ".mp3, .wav",
                },
            ),
        }
        labels = {
            **BaseTaskForm.Meta.labels,
            audio_field: _("Audio_file"),
        }


class AudioTaskCheckForm(BaseTaskCheckForm):
    class Meta(BaseTaskCheckForm.Meta):
        model = tasks.models.AudioTaskCheck

django_project/tasks/forms/image.py
__all__ = ()

from django import forms
from django.utils.translation import gettext_lazy as _

from tasks.forms.base import BaseTaskCheckForm, BaseTaskForm
import tasks.models


class ImageTaskForm(BaseTaskForm):
    class Meta(BaseTaskForm.Meta):
        model = tasks.models.ImageTask
        fields = BaseTaskForm.Meta.fields + [model.image.field.name]

        widgets = {
            model.image.field.name: forms.FileInput(
                attrs={
                    "class": "form-control",
                    "accept": "image/*",
                },
            ),
        }

        labels = {
            **BaseTaskForm.Meta.labels,
            model.image.field.name: _("Image"),
        }


class ImageTaskCheckForm(BaseTaskCheckForm):
    class Meta(BaseTaskCheckForm.Meta):
        model = tasks.models.ImageTaskCheck

django_project/tasks/routes/audio.py
from django.urls import path

import tasks.views

urlpatterns = [
    path(
        'my/',
        tasks.views.CustomerAudioTasksListView.as_view(),
        name='my-audio-tasks',
    ),
    path(
        'create/',
        tasks.views.AudioTaskCreateView.as_view(),
        name='audio-task-create',
    ),
    path(
        '<int:task_id>/',
        tasks.views.AudioTaskDetailView.as_view(),
        name='audio-task-detail',
    ),
    path(
        'my-checks/',
        tasks.views.PerformerAudioChecksListView.as_view(),
        name='my-audio-checks',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.AudioTaskCheckDetailView.as_view(),
        name='audio-check-detail',
    ),
    path(
        '<int:task_id>/check/',
        tasks.views.AudioTaskCheckPerformView.as_view(),
        name='audio-check-perform',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.AudioTaskCheckDetailView.as_view(),
        name='audio-check-detail',
    ),
]

django_project/tasks/routes/image.py
from django.urls import path

import tasks.views

urlpatterns = [
    path(
        'my/',
        tasks.views.CustomerImageTasksListView.as_view(),
        name='my-image-tasks',
    ),
    path(
        'create/',
        tasks.views.ImageTaskCreateView.as_view(),
        name='image-task-create',
    ),
    path(
        '<int:task_id>/',
        tasks.views.ImageTaskDetailView.as_view(),
        name='image-task-detail',
    ),
    path(
        'my-checks/',
        tasks.views.PerformerImageChecksListView.as_view(),
        name='my-image-checks',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.ImageTaskCheckDetailView.as_view(),
        name='image-check-detail',
    ),
    path(
        '<int:task_id>/check/',
        tasks.views.ImageTaskCheckPerformView.as_view(),
        name='image-check-perform',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.ImageTaskCheckDetailView.as_view(),
        name='image-check-detail',
    ),
]

django_project/tasks/routes/text.py
from django.urls import path

import tasks.views

urlpatterns = [
    path(
        'my/',
        tasks.views.CustomerTextTasksListView.as_view(),
        name='my-text-tasks',
    ),
    path(
        'create/',
        tasks.views.TextTaskCreateView.as_view(),
        name='text-task-create',
    ),
    path(
        '<int:task_id>/',
        tasks.views.TextTaskDetailView.as_view(),
        name='text-task-detail',
    ),
    path(
        'my-checks/',
        tasks.views.PerformerTextChecksListView.as_view(),
        name='my-text-checks',
    ),
    path(
        '<int:task_id>/check/',
        tasks.views.TextTaskCheckPerformView.as_view(),
        name='text-check-perform',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.TextTaskCheckDetailView.as_view(),
        name='text-check-detail',
    ),
]

django_project/tasks/views/audio.py
__all__ = ()

import tasks.forms
import tasks.models
from tasks.views.base import (
    BaseMyChecksListView,
    BaseMyTasksListView,
    BaseTaskCheckDetailView,
    BaseTaskCheckPerformView,
    BaseTaskCreateView,
    BaseTaskDetailView,
)


class CustomerAudioTasksListView(BaseMyTasksListView):
    model = tasks.models.AudioTask
    check_model = tasks.models.AudioTaskCheck
    template_name = 'tasks/audio/my_tasks.html'


class AudioTaskCreateView(BaseTaskCreateView):
    model = tasks.models.AudioTask
    form_class = tasks.forms.AudioTaskForm


class AudioTaskDetailView(BaseTaskDetailView):
    model = tasks.models.AudioTask
    check_model = tasks.models.AudioTaskCheck
    template_name = 'tasks/audio/task_detail.html'


class PerformerAudioChecksListView(BaseMyChecksListView):
    model = tasks.models.AudioTaskCheck
    task_model = tasks.models.AudioTask
    template_name = 'tasks/audio/my_checks.html'


class AudioTaskCheckPerformView(BaseTaskCheckPerformView):
    task_model = tasks.models.AudioTask
    check_model = tasks.models.AudioTaskCheck
    form_class = tasks.forms.AudioTaskCheckForm
    template_name = 'tasks/audio/check_perform.html'


class AudioTaskCheckDetailView(BaseTaskCheckDetailView):
    model = tasks.models.AudioTaskCheck
    task_model = tasks.models.AudioTask
    template_name = 'tasks/audio/check_detail.html'

django_project/tasks/views/base.py
__all__ = ()

from django.contrib import auth, messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DetailView, ListView, View

import users.mixins

User = auth.get_user_model()


class BaseMyTasksListView(
    LoginRequiredMixin,
    users.mixins.CustomerRequiredMixin,
    ListView,
):
    model = None
    check_model = None
    template_name = None
    context_object_name = "tasks"

    def get_queryset(self):
        queryset = self.model.objects.by_client(self.request.user)
        queryset = queryset.with_avg_ai_score(
            self.check_model,
        ).with_checks_count(self.check_model)

        created_at_field = self.model.created_at.field.name

        return queryset.order_by(f"-{created_at_field}")


class BaseTaskCreateView(
    LoginRequiredMixin,
    users.mixins.CustomerRequiredMixin,
    CreateView,
):
    model = None
    form_class = None
    template_name = "tasks/task_create.html"

    def form_valid(self, form):
        form.instance.client = self.request.user
        messages.success(self.request, _("Task_create_success"))
        return super().form_valid(form)


class BaseTaskDetailView(
    LoginRequiredMixin,
    users.mixins.CustomerRequiredMixin,
    DetailView,
):
    model = None
    check_model = None
    template_name = None
    pk_url_kwarg = "task_id"
    context_object_name = "task"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .prefetch_checks_with_performers(self.check_model)
            .with_checks_count(self.check_model)
            .with_avg_ai_score(self.check_model)
        )

    def get_object(self, queryset=None):
        task = super().get_object(queryset)
        if task.client_id != self.request.user.id:
            raise PermissionDenied(_("Not_owner_of_task"))

        return task


class BaseMyChecksListView(
    LoginRequiredMixin,
    users.mixins.PerformerRequiredMixin,
    ListView,
):
    model = None
    task_model = None
    template_name = None
    context_object_name = "checks"

    def get_queryset(self):
        all_needed_models_qs = self.model.objects.with_task_client(
            self.task_model,
        )
        task_title = (
            f"{self.model.task.field.name}__"
            f"{self.task_model.title.field.name}"
        )
        task_client_username = (
            f"{self.model.task.field.name}__"
            f"{self.task_model.client.field.name}__{User.username.field.name}"
        )

        return all_needed_models_qs.by_performer(self.request.user).only(
            task_title,
            task_client_username,
            self.model.ai_score.field.name,
            self.model.status.field.name,
            self.model.updated_at.field.name,
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_username = (
            f"{self.task_model.client.field.name}__{User.username.field.name}"
        )
        all_needed_models_qs = self.task_model.objects.with_client()

        context[
            "available_tasks"
        ] = all_needed_models_qs.available_for_performer(
            user=self.request.user,
            check_model=self.model,
        ).only(
            self.task_model.title.field.name,
            self.model.created_at.field.name,
            client_username,
        )

        return context


class BaseTaskCheckPerformView(
    LoginRequiredMixin,
    users.mixins.PerformerRequiredMixin,
    View,
):
    task_model = None
    check_model = None
    form_class = None
    template_name = None

    def dispatch(self, request, *args, **kwargs):
        self.task = get_object_or_404(
            self.task_model,
            pk=kwargs["task_id"],
        )

        if self.task.client == request.user:
            raise PermissionDenied(_("You_cant_check_task_created_by_you"))

        self.check_obj = self.check_model.objects.by_task_and_performer(
            self.task,
            request.user,
        ).first()

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if "form_attrs" in kwargs:
            form = self.form_class(
                instance=self.check_obj,
                **kwargs["form_attrs"],
            )
        else:
            form = self.form_class(instance=self.check_obj)

        return render(
            request,
            self.template_name,
            {"form": form, "task": self.task},
        )

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=self.check_obj)

        if form.is_valid():
            check = form.save(commit=False)
            check.task = self.task
            check.performer = request.user
            if "check_fields" in kwargs:
                for field, val in kwargs["check_fields"].items():
                    setattr(check, field, val)

            action = request.POST.get("action")

            if action == "publish":
                check.status = self.check_model.Status.PUBLISHED
                message = _("Check_published")
                check.save()
                messages.success(request, message)
                return redirect(check)

            if action == "save_draft":
                check.status = self.check_model.Status.DRAFT
                message = _("Draft_saved")
                check.save()
                messages.success(request, message)
                return redirect(request.path)

        return render(
            request,
            self.template_name,
            {"form": form, "task": self.task},
        )


class BaseTaskCheckDetailView(LoginRequiredMixin, DetailView):
    model = None
    task_model = None
    template_name = None
    pk_url_kwarg = "check_id"
    context_object_name = "check"

    def get_object(self, queryset=None):
        check = super().get_object(queryset)

        if (
            self.request.user != check.task.client
            and self.request.user != check.performer
        ):
            raise PermissionDenied(
                _("Not_viewer_of_check"),
            )

        return check

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_task_client(self.task_model)
            .with_performer()
        )

django_project/tasks/views/image.py
__all__ = ()

import tasks.forms
import tasks.models
from tasks.views.base import (
    BaseMyChecksListView,
    BaseMyTasksListView,
    BaseTaskCheckDetailView,
    BaseTaskCheckPerformView,
    BaseTaskCreateView,
    BaseTaskDetailView,
)


class CustomerImageTasksListView(BaseMyTasksListView):
    model = tasks.models.ImageTask
    check_model = tasks.models.ImageTaskCheck
    template_name = 'tasks/image/my_tasks.html'


class ImageTaskCreateView(BaseTaskCreateView):
    model = tasks.models.ImageTask
    form_class = tasks.forms.ImageTaskForm


class ImageTaskDetailView(BaseTaskDetailView):
    model = tasks.models.ImageTask
    check_model = tasks.models.ImageTaskCheck
    template_name = 'tasks/image/task_detail.html'


class PerformerImageChecksListView(BaseMyChecksListView):
    model = tasks.models.ImageTaskCheck
    task_model = tasks.models.ImageTask
    template_name = 'tasks/image/my_checks.html'


class ImageTaskCheckPerformView(BaseTaskCheckPerformView):
    task_model = tasks.models.ImageTask
    check_model = tasks.models.ImageTaskCheck
    form_class = tasks.forms.ImageTaskCheckForm
    template_name = 'tasks/image/check_perform.html'


class ImageTaskCheckDetailView(BaseTaskCheckDetailView):
    model = tasks.models.ImageTaskCheck
    task_model = tasks.models.ImageTask
    template_name = 'tasks/image/check_detail.html'

django_project/tasks/views/text.py
__all__ = ()

import core.utils
import tasks.forms
import tasks.models
from tasks.views.base import (
    BaseMyChecksListView,
    BaseMyTasksListView,
    BaseTaskCheckDetailView,
    BaseTaskCheckPerformView,
    BaseTaskCreateView,
    BaseTaskDetailView,
)


class CustomerTextTasksListView(BaseMyTasksListView):
    model = tasks.models.TextTask
    check_model = tasks.models.TextTaskCheck
    template_name = 'tasks/text/my_tasks.html'


class TextTaskCreateView(BaseTaskCreateView):
    model = tasks.models.TextTask
    form_class = tasks.forms.TextTaskForm


class TextTaskDetailView(BaseTaskDetailView):
    model = tasks.models.TextTask
    check_model = tasks.models.TextTaskCheck
    template_name = 'tasks/text/task_detail.html'


class PerformerTextChecksListView(BaseMyChecksListView):
    model = tasks.models.TextTaskCheck
    task_model = tasks.models.TextTask
    template_name = 'tasks/text/my_checks.html'


class TextTaskCheckPerformView(BaseTaskCheckPerformView):
    task_model = tasks.models.TextTask
    check_model = tasks.models.TextTaskCheck
    form_class = tasks.forms.TextTaskCheckForm
    template_name = 'tasks/text/check_perform.html'

    def get(self, request, *args, **kwargs):
        initial_content = self.task.content
        if self.check_obj and self.check_obj.annotated_content:
            initial_content = self.check_obj.annotated_content

        return super().get(
            request,
            form_attrs={
                'initial': {
                    'highlighted_content': initial_content,
                    'content': self.task.content,
                },
            },
        )

    def post(self, request, *args, **kwargs):
        raw_html = request.POST.getlist('highlighted_content')[0]

        if raw_html:
            final_content = core.utils.sanitize_html(raw_html)
        else:
            final_content = self.task.content

        return super().post(
            request,
            check_fields={
                'annotated_content': final_content,
            },
        )


class TextTaskCheckDetailView(BaseTaskCheckDetailView):
    model = tasks.models.TextTaskCheck
    task_model = tasks.models.TextTask
    template_name = 'tasks/text/check_detail.html'

django_project/templates/tasks/text/check_detail.html
{% extends "tasks/base/check_detail.html" %}
{% load i18n static %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/highlight_text.css' %}">
{% endblock extra_head %}

{% block task_content %}
  <p>{{ check.annotated_content|safe }}</p>
{% endblock task_content %}

{% block customer_return_link %}
  <a href="{% url 'tasks:text-task-detail' check.task.id %}" class="btn btn-secondary">{% translate "Back_to_task" %}</a>
{% endblock customer_return_link %}

{% block performer_return_link %}
  <a href="{% url 'tasks:my-text-checks' %}" class="btn btn-secondary">{% translate "Back_to_my_checks" %}</a>
{% endblock performer_return_link %}

django_project/templates/tasks/text/check_perform.html
{% extends 'tasks/base/check_perform.html' %}
{% load i18n %}

{% block task %}
  <div class="card text-start my-3 p-3 mx-auto col-11 roboto">
    <div id="task-content-container"
         aria-label="{% translate 'Task_content' %}"
         data-original-html="{{ task.content|escapejs }}"
         data-select-label="{% translate 'Select' %}">
      {% if form.instance and form.instance.annotated_content %}
        {{ form.instance.annotated_content|safe }}
      {% else %}
        {{ task.content|safe }}
      {% endif %}
    </div>
  </div>
{% endblock task %}

{% block input %}
  <input type="hidden"
         name="highlighted_content"
         id="highlighted_content"
         value="{% if form.instance and form.instance.annotated_content %}{{ form.instance.annotated_content|escapejs }}{% else %}{{ task.content|escapejs }}{% endif %}">
{% endblock input %}

django_project/templates/tasks/text/my_checks.html
{% extends "tasks/base/my_checks.html" %}
{% load i18n thumbnail %}

{% block title %}
  {% translate "My_text_checks" %}
{% endblock title %}

{% block task_content %}
  {{ task.content|safe|truncatechars_html:25 }}
{% endblock task_content %}
{% block completed_task_content %}
  {{ check.task.content|safe|truncatechars_html:25 }}
{% endblock completed_task_content %}

{% block task_title %}
  <a href="{% url 'tasks:text-check-perform' task.id %}" class="text-decoration-none stretched-link purple-hover">{{ task.title|truncatechars:25 }}</a>
{% endblock task_title %}
{% block completed_task_title %}
  <a class="text-decoration-none purple-hover" href="{% url 'tasks:text-check-perform' check.task.id %}">{{ check.task.title|truncatechars:25 }}</a>
{% endblock completed_task_title %}

{% block no_tasks %}
  {% translate "No_text_tasks" %}
{% endblock no_tasks %}

{% block no_checks %}
  {% translate "No_text_checks" %}
{% endblock no_checks %}

django_project/templates/tasks/text/my_tasks.html
{% extends "tasks/base/my_tasks.html" %}
{% load i18n static thumbnail %}

{% block title %}
  {% translate "My_text_tasks" %}
{% endblock title %}

{% block task_onclick %}
  onclick="window.location.href='{% url 'tasks:text-task-detail' task.id %}'"
{% endblock task_onclick %}

{% block task_title %}
  <a class="text-decoration-none purple-hover" href="{% url 'tasks:text-task-detail' task.id %}">{{ task.title }}</a>
{% endblock task_title %}

{% block task_content %}
  {{ task.content|safe|truncatechars_html:25 }}
{% endblock task_content %}

{% block no_tasks %}
  {% translate "No_text_tasks" %}
{% endblock no_tasks %}

django_project/templates/tasks/text/task_detail.html
{% extends "tasks/base/task_detail.html" %}
{% load i18n thumbnail %}

{% block title %}
  {{ task.title }}
{% endblock title %}

{% block task_content %}
  {{ task.content|safe|truncatechars_html:240 }}
{% endblock task_content %}

{% block task_content_expand %}
  <div class="modal fade" id="taskContentExpand" tabindex="-1" aria-labelledby="taskContentLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
      <div class="modal-content rounded-3">
        <div class="modal-header">
          <h5 class="modal-title" id="taskContentLabel">{% translate "Content" %} — {{ task.title }}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% translate 'Close' %}"></button>
        </div>
        <div class="modal-body">{{ task.content|safe }}</div>
      </div>
    </div>
  </div>
{% endblock task_content_expand %}

{% block view_details %}
  <a class="text-decoration-none purple-hover" href="{% url 'tasks:text-check-detail' check.id %}">{% translate "View_details" %}</a>
{% endblock view_details %}

{% block my_tasks %}
  <a class="text-decoration-none purple-hover" href="{% url 'tasks:my-text-tasks' %}">{% translate "My_tasks" %}</a>
{% endblock my_tasks %}