django_project/about/urls.py
__all__ = ()

import django.urls

import about.views


app_name = "about"

urlpatterns = [
    django.urls.path("", about.views.AboutView.as_view(), name="about"),
]

django_project/django_project/urls.py
__all__ = ()

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("tz_detect/", include("tz_detect.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("auth/", include("users.urls.auth_urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("users/", include("users.urls.users_urls")),
    path("tasks/", include("tasks.urls")),
    path("training/", include("training.urls")),
    path("", include("homepage.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += debug_toolbar.toolbar.debug_toolbar_urls()

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

django_project/tasks/urls.py
__all__ = ()

from django.urls import include, path

app_name = "tasks"

urlpatterns = [
    path("text/", include("tasks.routes.text")),
    path("image/", include("tasks.routes.image")),
    path("audio/", include("tasks.routes.audio")),
]

django_project/users/urls.py
__all__ = ()

from django.contrib.auth import views as django_views
from django.urls import path, reverse_lazy

from users import views


app_name = "users"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "signup/",
        views.SignUpView.as_view(),
        name="signup",
    ),
    path(
        "activate/<signed_username>/",
        views.ActivateUserView.as_view(),
        name="activate",
    ),
    path(
        "unlock-account/<signed_username>/",
        views.UnlockAccountView.as_view(),
        name="unlock-account",
    ),
    path(
        "profile/",
        views.ProfileView.as_view(),
        name="profile",
    ),
    path(
        "change-password/",
        views.PasswordChangeView.as_view(),
        name="change-password",
    ),
    path(
        "reset-password/",
        views.PasswordResetView.as_view(),
        name="reset-password",
    ),
    path(
        "reset-password/done/",
        django_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password-reset-done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        django_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password-reset-complete"),
        ),
        name="password-reset-confirm",
    ),
    path(
        "reset-password/complete/",
        django_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password-reset-complete",
    ),
    path(
        "user-detail/<int:pk>",
        views.UserDetailView.as_view(),
        name="user-detail",
    ),
]

django_project/tasks/models.py
__all__ = ()

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

import core.models
import tasks.fields
import tasks.managers


class BaseTask(core.models.TimeStampedModel):
    title = models.CharField(
        verbose_name=_("title"),
        max_length=255,
    )
    description = models.TextField(
        verbose_name=_("description"),
        blank=True,
    )

    class Meta:
        abstract = True
        ordering = ["-created_at"]

    def __str__(self):
        task_title = self.title
        if len(task_title) > 30:
            return task_title[:30] + "..."

        return task_title

    @property
    def ai_score(self):
        return self.checks.get_avg_ai_score()


class TextTask(BaseTask):
    client = tasks.fields.make_client_field("text")
    content = models.TextField(
        verbose_name=_("content"),
    )

    class Meta(BaseTask.Meta):
        verbose_name = _("text_task")
        verbose_name_plural = _("text_tasks")


class TextTaskCheck(core.models.TimeStampedModel):
    class Status(models.TextChoices):
        DRAFT = "draft", _("draft")
        PUBLISHED = "published", _("published")

    task = models.ForeignKey(
        TextTask,
        on_delete=models.CASCADE,
        related_name="checks",
        related_query_name="check",
        verbose_name=_("task"),
    )
    performer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="task_checks",
        related_query_name="task_check",
        verbose_name=_("performer"),
    )
    ai_score = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],
        verbose_name=_("ai_score"),
    )
    comment = models.TextField(
        blank=True,
        verbose_name=_("comment"),
    )
    status = models.CharField(
        max_length=15,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name=_("status"),
    )

    objects = tasks.managers.TaskCheckManager()

    class Meta:
        verbose_name = _("task_check")
        verbose_name_plural = _("task_checks")
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["task", "performer"],
                name="unique_task_performer",
            ),
        ]

    def __str__(self):
        task_title = self.task.title
        if len(task_title) > 20:
            task_title = task_title[:20] + "..."

        return (
            f"{self.task.title} | {self.performer.username} ({self.ai_score}%)"
        )

django_project/tasks/forms/image.py
__all__ = ()

from django import forms
from django.utils.translation import gettext_lazy as _

from tasks.forms.base import BaseTaskCheckForm, BaseTaskForm
import tasks.models


class ImageTaskForm(BaseTaskForm):
    class Meta(BaseTaskForm.Meta):
        model = tasks.models.ImageTask
        fields = BaseTaskForm.Meta.fields + [model.image.field.name]

        widgets = {
            model.image.field.name: forms.FileInput(
                attrs={
                    "class": "form-control",
                    "accept": "image/*",
                },
            ),
        }

        labels = {
            **BaseTaskForm.Meta.labels,
            model.image.field.name: _("Image"),
        }


class ImageTaskCheckForm(BaseTaskCheckForm):
    class Meta(BaseTaskCheckForm.Meta):
        model = tasks.models.ImageTaskCheck

django_project/tasks/routes/audio.py
from django.urls import path

import tasks.views

urlpatterns = [
    path(
        'my/',
        tasks.views.CustomerAudioTasksListView.as_view(),
        name='my-audio-tasks',
    ),
    path(
        'create/',
        tasks.views.AudioTaskCreateView.as_view(),
        name='audio-task-create',
    ),
    path(
        '<int:task_id>/',
        tasks.views.AudioTaskDetailView.as_view(),
        name='audio-task-detail',
    ),
    path(
        'my-checks/',
        tasks.views.PerformerAudioChecksListView.as_view(),
        name='my-audio-checks',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.AudioTaskCheckDetailView.as_view(),
        name='audio-check-detail',
    ),
    path(
        '<int:task_id>/check/',
        tasks.views.AudioTaskCheckPerformView.as_view(),
        name='audio-check-perform',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.AudioTaskCheckDetailView.as_view(),
        name='audio-check-detail',
    ),
]

django_project/tasks/routes/image.py
from django.urls import path

import tasks.views

urlpatterns = [
    path(
        'my/',
        tasks.views.CustomerImageTasksListView.as_view(),
        name='my-image-tasks',
    ),
    path(
        'create/',
        tasks.views.ImageTaskCreateView.as_view(),
        name='image-task-create',
    ),
    path(
        '<int:task_id>/',
        tasks.views.ImageTaskDetailView.as_view(),
        name='image-task-detail',
    ),
    path(
        'my-checks/',
        tasks.views.PerformerImageChecksListView.as_view(),
        name='my-image-checks',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.ImageTaskCheckDetailView.as_view(),
        name='image-check-detail',
    ),
    path(
        '<int:task_id>/check/',
        tasks.views.ImageTaskCheckPerformView.as_view(),
        name='image-check-perform',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.ImageTaskCheckDetailView.as_view(),
        name='image-check-detail',
    ),
]

django_project/tasks/routes/text.py
from django.urls import path

import tasks.views

urlpatterns = [
    path(
        'my/',
        tasks.views.CustomerTextTasksListView.as_view(),
        name='my-text-tasks',
    ),
    path(
        'create/',
        tasks.views.TextTaskCreateView.as_view(),
        name='text-task-create',
    ),
    path(
        '<int:task_id>/',
        tasks.views.TextTaskDetailView.as_view(),
        name='text-task-detail',
    ),
    path(
        'my-checks/',
        tasks.views.PerformerTextChecksListView.as_view(),
        name='my-text-checks',
    ),
    path(
        '<int:task_id>/check/',
        tasks.views.TextTaskCheckPerformView.as_view(),
        name='text-check-perform',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.TextTaskCheckDetailView.as_view(),
        name='text-check-detail',
    ),
]

django_project/tasks/views/audio.py
__all__ = ()

import tasks.forms
import tasks.models
from tasks.views.base import (
    BaseMyChecksListView,
    BaseMyTasksListView,
    BaseTaskCheckDetailView,
    BaseTaskCheckPerformView,
    BaseTaskCreateView,
    BaseTaskDetailView,
)


class CustomerAudioTasksListView(BaseMyTasksListView):
    model = tasks.models.AudioTask
    check_model = tasks.models.AudioTaskCheck
    template_name = 'tasks/audio/my_tasks.html'


class AudioTaskCreateView(BaseTaskCreateView):
    model = tasks.models.AudioTask
    form_class = tasks.forms.AudioTaskForm


class AudioTaskDetailView(BaseTaskDetailView):
    model = tasks.models.AudioTask
    check_model = tasks.models.AudioTaskCheck
    template_name = 'tasks/audio/task_detail.html'


class PerformerAudioChecksListView(BaseMyChecksListView):
    model = tasks.models.AudioTaskCheck
    task_model = tasks.models.AudioTask
    template_name = 'tasks/audio/my_checks.html'


class AudioTaskCheckPerformView(BaseTaskCheckPerformView):
    task_model = tasks.models.AudioTask
    check_model = tasks.models.AudioTaskCheck
    form_class = tasks.forms.AudioTaskCheckForm
    template_name = 'tasks/audio/check_perform.html'


class AudioTaskCheckDetailView(BaseTaskCheckDetailView):
    model = tasks.models.AudioTaskCheck
    task_model = tasks.models.AudioTask
    template_name = 'tasks/audio/check_detail.html'

django_project/tasks/views/base.py
__all__ = ()

from django.contrib import auth, messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DetailView, ListView, View

import users.mixins

User = auth.get_user_model()


class BaseMyTasksListView(
    LoginRequiredMixin,
    users.mixins.CustomerRequiredMixin,
    ListView,
):
    model = None
    check_model = None
    template_name = None
    context_object_name = "tasks"

    def get_queryset(self):
        queryset = self.model.objects.by_client(self.request.user)
        queryset = queryset.with_avg_ai_score(
            self.check_model,
        ).with_checks_count(self.check_model)

        created_at_field = self.model.created_at.field.name

        return queryset.order_by(f"-{created_at_field}")


class BaseTaskCreateView(
    LoginRequiredMixin,
    users.mixins.CustomerRequiredMixin,
    CreateView,
):
    model = None
    form_class = None
    template_name = "tasks/task_create.html"

    def form_valid(self, form):
        form.instance.client = self.request.user
        messages.success(self.request, _("Task_create_success"))
        return super().form_valid(form)


class BaseTaskDetailView(
    LoginRequiredMixin,
    users.mixins.CustomerRequiredMixin,
    DetailView,
):
    model = None
    check_model = None
    template_name = None
    pk_url_kwarg = "task_id"
    context_object_name = "task"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .prefetch_checks_with_performers(self.check_model)
            .with_checks_count(self.check_model)
            .with_avg_ai_score(self.check_model)
        )

    def get_object(self, queryset=None):
        task = super().get_object(queryset)
        if task.client_id != self.request.user.id:
            raise PermissionDenied(_("Not_owner_of_task"))

        return task


class BaseMyChecksListView(
    LoginRequiredMixin,
    users.mixins.PerformerRequiredMixin,
    ListView,
):
    model = None
    task_model = None
    template_name = None
    context_object_name = "checks"

    def get_queryset(self):
        all_needed_models_qs = self.model.objects.with_task_client(
            self.task_model,
        )
        task_title = (
            f"{self.model.task.field.name}__"
            f"{self.task_model.title.field.name}"
        )
        task_client_username = (
            f"{self.model.task.field.name}__"
            f"{self.task_model.client.field.name}__{User.username.field.name}"
        )

        return all_needed_models_qs.by_performer(self.request.user).only(
            task_title,
            task_client_username,
            self.model.ai_score.field.name,
            self.model.status.field.name,
            self.model.updated_at.field.name,
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_username = (
            f"{self.task_model.client.field.name}__{User.username.field.name}"
        )
        all_needed_models_qs = self.task_model.objects.with_client()

        context[
            "available_tasks"
        ] = all_needed_models_qs.available_for_performer(
            user=self.request.user,
            check_model=self.model,
        ).only(
            self.task_model.title.field.name,
            self.model.created_at.field.name,
            client_username,
        )

        return context


class BaseTaskCheckPerformView(
    LoginRequiredMixin,
    users.mixins.PerformerRequiredMixin,
    View,
):
    task_model = None
    check_model = None
    form_class = None
    template_name = None

    def dispatch(self, request, *args, **kwargs):
        self.task = get_object_or_404(
            self.task_model,
            pk=kwargs["task_id"],
        )

        if self.task.client == request.user:
            raise PermissionDenied(_("You_cant_check_task_created_by_you"))

        self.check_obj = self.check_model.objects.by_task_and_performer(
            self.task,
            request.user,
        ).first()

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if "form_attrs" in kwargs:
            form = self.form_class(
                instance=self.check_obj,
                **kwargs["form_attrs"],
            )
        else:
            form = self.form_class(instance=self.check_obj)

        return render(
            request,
            self.template_name,
            {"form": form, "task": self.task},
        )

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=self.check_obj)

        if form.is_valid():
            check = form.save(commit=False)
            check.task = self.task
            check.performer = request.user
            if "check_fields" in kwargs:
                for field, val in kwargs["check_fields"].items():
                    setattr(check, field, val)

            action = request.POST.get("action")

            if action == "publish":
                check.status = self.check_model.Status.PUBLISHED
                message = _("Check_published")
                check.save()
                messages.success(request, message)
                return redirect(check)

            if action == "save_draft":
                check.status = self.check_model.Status.DRAFT
                message = _("Draft_saved")
                check.save()
                messages.success(request, message)
                return redirect(request.path)

        return render(
            request,
            self.template_name,
            {"form": form, "task": self.task},
        )


class BaseTaskCheckDetailView(LoginRequiredMixin, DetailView):
    model = None
    task_model = None
    template_name = None
    pk_url_kwarg = "check_id"
    context_object_name = "check"

    def get_object(self, queryset=None):
        check = super().get_object(queryset)

        if (
            self.request.user != check.task.client
            and self.request.user != check.performer
        ):
            raise PermissionDenied(
                _("Not_viewer_of_check"),
            )

        return check

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_task_client(self.task_model)
            .with_performer()
        )

django_project/templates/tasks/base/check_perform.html
{% extends 'base.html' %}
{% load i18n static %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/highlight_text.css' %}">
{% endblock extra_head %}

{% block content %}
  <div class="container">
    <h2 class="text-center">{% translate "Task_check" %}: {{ task.title }}</h2>

    {% block task %}
    {% endblock task %}

    <form method="post">
      {% csrf_token %}
      {{ form.media }}
      {% block input %}
      {% endblock input %}
      {{ form.as_p }}
      <hr>
      {% if form.instance.status == 'published' %}
        <div class="alert alert-success">{% translate "Check_already_published" %}</div>
        <a href="{% url 'tasks:my-image-checks' %}" class="btn btn-secondary">{% translate "Return" %}</a>
      {% else %}
        <div class="d-flex gap-2">
          <button type="submit" name="action" value="save_draft" class="btn btn-secondary">{% translate "Save_draft" %}</button>

          <button type="submit"
                  name="action"
                  value="publish"
                  class="btn btn-primary"
                  data-confirm-message="{% translate 'Action_irreversible'|escapejs %}"
                  onclick="return confirm(this.getAttribute('data-confirm-message'));">{% translate "Send_check" %}</button>
        </div>
      {% endif %}
    </form>
  </div>

  <script src="{% static 'js/highlight_text.js' %}"></script>
{% endblock content %}

django_project/templates/tasks/base/my_checks.html
{% extends "base.html" %}
{% load i18n static thumbnail %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/tasks.css' %}">
{% endblock extra_head %}

{% block content %}
  {% include "includes/tasks_header.html" %}

  <main class="container-fluid mb-5">
    <nav>
      <ul class="nav nav-tabs nav-fill mb-4" id="taskTabs" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active fw-normal"
                  id="available-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#available-pane"
                  type="button"
                  role="tab"
                  aria-controls="available-pane"
                  aria-selected="true">
            <i class="bi bi-inbox me-1 fs-6" aria-hidden="true"></i>
            {% translate "Available_tasks" %}
            {% if available_tasks %}
              <span class="badge bg-primary rounded-pill ms-2" aria-label="{% translate 'Available_tasks_count' %}">{{ available_tasks.count }}</span>
            {% endif %}
          </button>
        </li>

        <li class="nav-item" role="presentation">
          <button class="nav-link fw-normal"
                  id="completed-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#completed-pane"
                  type="button"
                  role="tab"
                  aria-controls="completed-pane"
                  aria-selected="false">
            <i class="bi bi-check2-circle me-1 fs-6" aria-hidden="true"></i>
            {% translate "Completed_tasks" %}
          </button>
        </li>
      </ul>
    </nav>

    <div class="tab-content" id="taskTabsContent">
      <section class="tab-pane fade show active" id="available-pane" role="tabpanel" aria-labelledby="available-tab" tabindex="0">
        {% if available_tasks %}
          <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% for task in available_tasks %}
              <article class="col">
                <div class="card h-100 shadow-sm hover-lift task-card">
                  <header class="card-header bg-transparent d-flex justify-content-between align-items-center text-muted small border-bottom-0 pt-3">
                    <div class="d-flex align-items-center gap-2">
                      <i class="bi bi-person-circle" aria-hidden="true"></i>
                      <span class="client-name" title="{% translate 'Client' %}">{{ task.client.username }}</span>
                    </div>
                    <time class="task-date" datetime="{{ task.created_at|date:'c' }}">{{ task.created_at|date:"d.m.Y" }}</time>
                  </header>

                  <div class="card-body">
                    <h3 class="card-title text-truncate">
                      {% block task_title %}
                      {% endblock task_title %}
                    </h3>

                    <div class="card-text text-muted small mt-2 task-content-preview">
                      {% block task_content %}
                      {% endblock task_content %}
                    </div>
                  </div>

                  <footer class="card-footer bg-transparent border-top-0 pb-3">
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="d-flex align-items-center gap-2">
                        {% if task.ai_score is not None %}
                          {% if task.ai_score >= 70 %}
                            <span class="badge text-danger border border-danger px-2 py-1">
                              <i class="bi bi-cpu me-1"></i><span class="fs-6 fw-normal">{{ task.ai_score|floatformat:0 }}%</span>
                            </span>
                          {% elif task.ai_score >= 30 %}
                            <span class="badge text-warning border border-warning px-2 py-1">
                              <i class="bi bi-cpu me-1"></i><span class="fs-6 fw-normal">{{ task.ai_score|floatformat:0 }}%</span>
                            </span>
                          {% else %}
                            <span class="badge text-success border border-success px-2 py-1">
                              <i class="bi bi-cpu me-1"></i><span class="fs-6 fw-normal">{{ task.ai_score|floatformat:0 }}%</span>
                            </span>
                          {% endif %}
                        {% else %}
                          <span class="badge text-secondary border px-2 py-1" title="{% translate 'Not_checked' %}">
                            <i class="bi bi-hourglass me-1"></i>{% translate "Not_checked" %}
                          </span>
                        {% endif %}
                      </div>

                      <div class="text-muted small d-flex align-items-center gap-2" title="{% translate 'Checks_count' %}">
                        <i class="bi bi-people" aria-hidden="true"></i>
                        <span>{{ task.checks_count|default:0 }}</span>
                      </div>
                    </div>
                  </footer>
                </div>
              </article>
            {% endfor %}
          </div>
        {% else %}
          <div class="empty-state border rounded text-center py-5">
            <i class="bi bi-clipboard-x display-5 d-block mb-3"></i>
            <h4 class="mb-2">
              {% block no_tasks %}
              {% endblock no_tasks %}
            </h4>
            <p class="text-muted mb-0">{% translate "No_tasks_text" %}</p>
          </div>
        {% endif %}
      </section>

      <section class="tab-pane fade" id="completed-pane" role="tabpanel" aria-labelledby="completed-tab" tabindex="0">
        {% if checks %}
          <div class="card shadow-sm border-0">
            <div class="table-responsive">
              <table class="table table-hover align-middle mb-0">
                <thead class="bg-body-tertiary">
                  <tr>
                    <th scope="col" class="ps-4">ID</th>
                    <th scope="col">{% translate "Title" %}</th>
                    <th scope="col">{% translate "Client" %}</th>
                    <th scope="col" class="d-none d-md-table-cell">{% translate "Date" %}</th>
                    <th scope="col">{% translate "Status" %}</th>
                    <th scope="col" class="pe-4 text-end">{% translate "AI_score" %}</th>
                  </tr>
                </thead>
                <tbody>
                  {% for check in checks %}
                    <tr>
                      <td class="ps-4 text-muted small">#{{ check.id }}</td>

                      <td>
                        <div class="fw-medium text-truncate">
                          {% block completed_task_title %}
                          {% endblock completed_task_title %}
                        </div>
                      </td>

                      <td class="small">
                        <div role="button" onclick="window.location.href='{% url 'users:user-detail' check.task.client.id %}'">
                          {% if check.task.client.avatar %}
                            {% thumbnail check.task.client.avatar "30x30" crop="center" upscale=True as avatar %}
                              <img src="{{ avatar.url }}" alt="Avatar" width="{{ avatar.width }}" height="{{ avatar.height }}" class="rounded-circle">
                            {% endthumbnail %}
                          {% else %}
                            <img src="{% static 'img/no_avatar.png' %}" alt="{% translate 'Avatar_not_found' %}" width="30" height="30" class="rounded-circle">
                          {% endif %}
                          {{ check.task.client.username }}
                        </div>
                      </td>

                      <td class="text-muted small d-none d-md-table-cell">
                        <time datetime="{{ check.updated_at|date:'c' }}">{{ check.updated_at|date:"d.m.Y" }}</time>
                      </td>

                      <td>
                        <span class="badge bg-body-tertiary text-body fw-normal fs-6">{{ check.get_status_display }}</span>
                      </td>

                      <td class="pe-4 text-end">
                        {% if check.ai_score is not None %}
                          <span class="fw-bold {% if check.ai_score >= 70 %}text-danger{% elif check.ai_score >= 30 %}text-warning{% else %}text-success{% endif %}">
                            {{ check.ai_score|floatformat:1 }}%
                          </span>
                        {% else %}
                          <span class="text-muted">-</span>
                        {% endif %}
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        {% else %}
          <div class="empty-state border rounded text-center py-5">
            <div class="display-1 text-muted mb-3" aria-hidden="true">
              <i class="bi bi-journal-x"></i>
            </div>
            <h4 class="mb-2">
              {% block no_checks %}
                {% translate "No_check_history" %}
              {% endblock no_checks %}
            </h4>
          </div>
        {% endif %}
      </section>
    </div>
  </main>
{% endblock content %}