django_project/about/urls.py
__all__ = ()

import django.urls

import about.views


app_name = "about"

urlpatterns = [
    django.urls.path("", about.views.AboutView.as_view(), name="about"),
]

django_project/django_project/urls.py
__all__ = ()

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("tz_detect/", include("tz_detect.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("auth/", include("users.urls.auth_urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls")),
    path("feedback/", include("feedback.urls")),
    path("users/", include("users.urls.users_urls")),
    path("tasks/", include("tasks.urls")),
    path("training/", include("training.urls")),
    path("", include("homepage.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += debug_toolbar.toolbar.debug_toolbar_urls()

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

django_project/homepage/urls.py
__all__ = ()

import django.urls

import homepage.views


app_name = "homepage"

urlpatterns = [
    django.urls.path("", homepage.views.IndexView.as_view(), name="index"),
]

django_project/tasks/urls.py
__all__ = ()

from django.urls import include, path

app_name = "tasks"

urlpatterns = [
    path("text/", include("tasks.routes.text")),
    path("image/", include("tasks.routes.image")),
    path("audio/", include("tasks.routes.audio")),
]

django_project/tasks/models.py
__all__ = ()

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

import core.models
import tasks.fields
import tasks.managers


class BaseTask(core.models.TimeStampedModel):
    title = models.CharField(
        verbose_name=_("title"),
        max_length=255,
    )
    description = models.TextField(
        verbose_name=_("description"),
        blank=True,
    )

    class Meta:
        abstract = True
        ordering = ["-created_at"]

    def __str__(self):
        task_title = self.title
        if len(task_title) > 30:
            return task_title[:30] + "..."

        return task_title

    @property
    def ai_score(self):
        return self.checks.get_avg_ai_score()


class TextTask(BaseTask):
    client = tasks.fields.make_client_field("text")
    content = models.TextField(
        verbose_name=_("content"),
    )

    class Meta(BaseTask.Meta):
        verbose_name = _("text_task")
        verbose_name_plural = _("text_tasks")


class TextTaskCheck(core.models.TimeStampedModel):
    class Status(models.TextChoices):
        DRAFT = "draft", _("draft")
        PUBLISHED = "published", _("published")

    task = models.ForeignKey(
        TextTask,
        on_delete=models.CASCADE,
        related_name="checks",
        related_query_name="check",
        verbose_name=_("task"),
    )
    performer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="task_checks",
        related_query_name="task_check",
        verbose_name=_("performer"),
    )
    ai_score = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],
        verbose_name=_("ai_score"),
    )
    comment = models.TextField(
        blank=True,
        verbose_name=_("comment"),
    )
    status = models.CharField(
        max_length=15,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name=_("status"),
    )

    objects = tasks.managers.TaskCheckManager()

    class Meta:
        verbose_name = _("task_check")
        verbose_name_plural = _("task_checks")
        ordering = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["task", "performer"],
                name="unique_task_performer",
            ),
        ]

    def __str__(self):
        task_title = self.task.title
        if len(task_title) > 20:
            task_title = task_title[:20] + "..."

        return (
            f"{self.task.title} | {self.performer.username} ({self.ai_score}%)"
        )

django_project/tasks/forms/audio.py
__all__ = ()

from django import forms
from django.utils.translation import gettext_lazy as _

from tasks.forms.base import BaseTaskCheckForm, BaseTaskForm
import tasks.models


class AudioTaskForm(BaseTaskForm):
    class Meta(BaseTaskForm.Meta):
        model = tasks.models.AudioTask

        audio_field = model.audio.field.name

        fields = BaseTaskForm.Meta.fields + [
            audio_field,
        ]
        widgets = {
            audio_field: forms.FileInput(
                attrs={
                    "class": "form-control",
                    "accept": ".mp3, .wav",
                },
            ),
        }
        labels = {
            **BaseTaskForm.Meta.labels,
            audio_field: _("Audio_file"),
        }


class AudioTaskCheckForm(BaseTaskCheckForm):
    class Meta(BaseTaskCheckForm.Meta):
        model = tasks.models.AudioTaskCheck

django_project/tasks/routes/audio.py
from django.urls import path

import tasks.views

urlpatterns = [
    path(
        'my/',
        tasks.views.CustomerAudioTasksListView.as_view(),
        name='my-audio-tasks',
    ),
    path(
        'create/',
        tasks.views.AudioTaskCreateView.as_view(),
        name='audio-task-create',
    ),
    path(
        '<int:task_id>/',
        tasks.views.AudioTaskDetailView.as_view(),
        name='audio-task-detail',
    ),
    path(
        'my-checks/',
        tasks.views.PerformerAudioChecksListView.as_view(),
        name='my-audio-checks',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.AudioTaskCheckDetailView.as_view(),
        name='audio-check-detail',
    ),
    path(
        '<int:task_id>/check/',
        tasks.views.AudioTaskCheckPerformView.as_view(),
        name='audio-check-perform',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.AudioTaskCheckDetailView.as_view(),
        name='audio-check-detail',
    ),
]

django_project/tasks/routes/image.py
from django.urls import path

import tasks.views

urlpatterns = [
    path(
        'my/',
        tasks.views.CustomerImageTasksListView.as_view(),
        name='my-image-tasks',
    ),
    path(
        'create/',
        tasks.views.ImageTaskCreateView.as_view(),
        name='image-task-create',
    ),
    path(
        '<int:task_id>/',
        tasks.views.ImageTaskDetailView.as_view(),
        name='image-task-detail',
    ),
    path(
        'my-checks/',
        tasks.views.PerformerImageChecksListView.as_view(),
        name='my-image-checks',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.ImageTaskCheckDetailView.as_view(),
        name='image-check-detail',
    ),
    path(
        '<int:task_id>/check/',
        tasks.views.ImageTaskCheckPerformView.as_view(),
        name='image-check-perform',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.ImageTaskCheckDetailView.as_view(),
        name='image-check-detail',
    ),
]

django_project/tasks/routes/text.py
from django.urls import path

import tasks.views

urlpatterns = [
    path(
        'my/',
        tasks.views.CustomerTextTasksListView.as_view(),
        name='my-text-tasks',
    ),
    path(
        'create/',
        tasks.views.TextTaskCreateView.as_view(),
        name='text-task-create',
    ),
    path(
        '<int:task_id>/',
        tasks.views.TextTaskDetailView.as_view(),
        name='text-task-detail',
    ),
    path(
        'my-checks/',
        tasks.views.PerformerTextChecksListView.as_view(),
        name='my-text-checks',
    ),
    path(
        '<int:task_id>/check/',
        tasks.views.TextTaskCheckPerformView.as_view(),
        name='text-check-perform',
    ),
    path(
        'check/<int:check_id>/',
        tasks.views.TextTaskCheckDetailView.as_view(),
        name='text-check-detail',
    ),
]

django_project/tasks/views/audio.py
__all__ = ()

import tasks.forms
import tasks.models
from tasks.views.base import (
    BaseMyChecksListView,
    BaseMyTasksListView,
    BaseTaskCheckDetailView,
    BaseTaskCheckPerformView,
    BaseTaskCreateView,
    BaseTaskDetailView,
)


class CustomerAudioTasksListView(BaseMyTasksListView):
    model = tasks.models.AudioTask
    check_model = tasks.models.AudioTaskCheck
    template_name = 'tasks/audio/my_tasks.html'


class AudioTaskCreateView(BaseTaskCreateView):
    model = tasks.models.AudioTask
    form_class = tasks.forms.AudioTaskForm


class AudioTaskDetailView(BaseTaskDetailView):
    model = tasks.models.AudioTask
    check_model = tasks.models.AudioTaskCheck
    template_name = 'tasks/audio/task_detail.html'


class PerformerAudioChecksListView(BaseMyChecksListView):
    model = tasks.models.AudioTaskCheck
    task_model = tasks.models.AudioTask
    template_name = 'tasks/audio/my_checks.html'


class AudioTaskCheckPerformView(BaseTaskCheckPerformView):
    task_model = tasks.models.AudioTask
    check_model = tasks.models.AudioTaskCheck
    form_class = tasks.forms.AudioTaskCheckForm
    template_name = 'tasks/audio/check_perform.html'


class AudioTaskCheckDetailView(BaseTaskCheckDetailView):
    model = tasks.models.AudioTaskCheck
    task_model = tasks.models.AudioTask
    template_name = 'tasks/audio/check_detail.html'

django_project/tasks/views/base.py
__all__ = ()

from django.contrib import auth, messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DetailView, ListView, View

import users.mixins

User = auth.get_user_model()


class BaseMyTasksListView(
    LoginRequiredMixin,
    users.mixins.CustomerRequiredMixin,
    ListView,
):
    model = None
    check_model = None
    template_name = None
    context_object_name = "tasks"

    def get_queryset(self):
        queryset = self.model.objects.by_client(self.request.user)
        queryset = queryset.with_avg_ai_score(
            self.check_model,
        ).with_checks_count(self.check_model)

        created_at_field = self.model.created_at.field.name

        return queryset.order_by(f"-{created_at_field}")


class BaseTaskCreateView(
    LoginRequiredMixin,
    users.mixins.CustomerRequiredMixin,
    CreateView,
):
    model = None
    form_class = None
    template_name = "tasks/task_create.html"

    def form_valid(self, form):
        form.instance.client = self.request.user
        messages.success(self.request, _("Task_create_success"))
        return super().form_valid(form)


class BaseTaskDetailView(
    LoginRequiredMixin,
    users.mixins.CustomerRequiredMixin,
    DetailView,
):
    model = None
    check_model = None
    template_name = None
    pk_url_kwarg = "task_id"
    context_object_name = "task"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .prefetch_checks_with_performers(self.check_model)
            .with_checks_count(self.check_model)
            .with_avg_ai_score(self.check_model)
        )

    def get_object(self, queryset=None):
        task = super().get_object(queryset)
        if task.client_id != self.request.user.id:
            raise PermissionDenied(_("Not_owner_of_task"))

        return task


class BaseMyChecksListView(
    LoginRequiredMixin,
    users.mixins.PerformerRequiredMixin,
    ListView,
):
    model = None
    task_model = None
    template_name = None
    context_object_name = "checks"

    def get_queryset(self):
        all_needed_models_qs = self.model.objects.with_task_client(
            self.task_model,
        )
        task_title = (
            f"{self.model.task.field.name}__"
            f"{self.task_model.title.field.name}"
        )
        task_client_username = (
            f"{self.model.task.field.name}__"
            f"{self.task_model.client.field.name}__{User.username.field.name}"
        )

        return all_needed_models_qs.by_performer(self.request.user).only(
            task_title,
            task_client_username,
            self.model.ai_score.field.name,
            self.model.status.field.name,
            self.model.updated_at.field.name,
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_username = (
            f"{self.task_model.client.field.name}__{User.username.field.name}"
        )
        all_needed_models_qs = self.task_model.objects.with_client()

        context[
            "available_tasks"
        ] = all_needed_models_qs.available_for_performer(
            user=self.request.user,
            check_model=self.model,
        ).only(
            self.task_model.title.field.name,
            self.model.created_at.field.name,
            client_username,
        )

        return context


class BaseTaskCheckPerformView(
    LoginRequiredMixin,
    users.mixins.PerformerRequiredMixin,
    View,
):
    task_model = None
    check_model = None
    form_class = None
    template_name = None

    def dispatch(self, request, *args, **kwargs):
        self.task = get_object_or_404(
            self.task_model,
            pk=kwargs["task_id"],
        )

        if self.task.client == request.user:
            raise PermissionDenied(_("You_cant_check_task_created_by_you"))

        self.check_obj = self.check_model.objects.by_task_and_performer(
            self.task,
            request.user,
        ).first()

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if "form_attrs" in kwargs:
            form = self.form_class(
                instance=self.check_obj,
                **kwargs["form_attrs"],
            )
        else:
            form = self.form_class(instance=self.check_obj)

        return render(
            request,
            self.template_name,
            {"form": form, "task": self.task},
        )

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=self.check_obj)

        if form.is_valid():
            check = form.save(commit=False)
            check.task = self.task
            check.performer = request.user
            if "check_fields" in kwargs:
                for field, val in kwargs["check_fields"].items():
                    setattr(check, field, val)

            action = request.POST.get("action")

            if action == "publish":
                check.status = self.check_model.Status.PUBLISHED
                message = _("Check_published")
                check.save()
                messages.success(request, message)
                return redirect(check)

            if action == "save_draft":
                check.status = self.check_model.Status.DRAFT
                message = _("Draft_saved")
                check.save()
                messages.success(request, message)
                return redirect(request.path)

        return render(
            request,
            self.template_name,
            {"form": form, "task": self.task},
        )


class BaseTaskCheckDetailView(LoginRequiredMixin, DetailView):
    model = None
    task_model = None
    template_name = None
    pk_url_kwarg = "check_id"
    context_object_name = "check"

    def get_object(self, queryset=None):
        check = super().get_object(queryset)

        if (
            self.request.user != check.task.client
            and self.request.user != check.performer
        ):
            raise PermissionDenied(
                _("Not_viewer_of_check"),
            )

        return check

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .with_task_client(self.task_model)
            .with_performer()
        )

django_project/tasks/views/image.py
__all__ = ()

import tasks.forms
import tasks.models
from tasks.views.base import (
    BaseMyChecksListView,
    BaseMyTasksListView,
    BaseTaskCheckDetailView,
    BaseTaskCheckPerformView,
    BaseTaskCreateView,
    BaseTaskDetailView,
)


class CustomerImageTasksListView(BaseMyTasksListView):
    model = tasks.models.ImageTask
    check_model = tasks.models.ImageTaskCheck
    template_name = 'tasks/image/my_tasks.html'


class ImageTaskCreateView(BaseTaskCreateView):
    model = tasks.models.ImageTask
    form_class = tasks.forms.ImageTaskForm


class ImageTaskDetailView(BaseTaskDetailView):
    model = tasks.models.ImageTask
    check_model = tasks.models.ImageTaskCheck
    template_name = 'tasks/image/task_detail.html'


class PerformerImageChecksListView(BaseMyChecksListView):
    model = tasks.models.ImageTaskCheck
    task_model = tasks.models.ImageTask
    template_name = 'tasks/image/my_checks.html'


class ImageTaskCheckPerformView(BaseTaskCheckPerformView):
    task_model = tasks.models.ImageTask
    check_model = tasks.models.ImageTaskCheck
    form_class = tasks.forms.ImageTaskCheckForm
    template_name = 'tasks/image/check_perform.html'


class ImageTaskCheckDetailView(BaseTaskCheckDetailView):
    model = tasks.models.ImageTaskCheck
    task_model = tasks.models.ImageTask
    template_name = 'tasks/image/check_detail.html'

django_project/templates/tasks/my_text_checks.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% translate "my_checks" %}
{% endblock title %}

{% block content %}
  <h2>{% translate "available_tasks" %}</h2>
  {% comment %} <h2>Available tasks</h2> {% endcomment %}
  {% if available_tasks %}
    <table>
      <thead>
        <tr>
          <th>{% translate "Task" %}</th>
          {% comment %} <th>Task</th> {% endcomment %}
          <th>{% translate "created_at" %}</th>
          {% comment %} <th>Created</th> {% endcomment %}
          <th>{% translate "Action" %}</th>
          {% comment %} <th>Action</th> {% endcomment %}
        </tr>
      </thead>
      <tbody>
        {% for task in available_tasks %}
          <tr>
            <td>{{ task.title }}</td>
            <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
            <td>
              <a href="{% url 'tasks:text-check-perform' task.id %}">
                {% translate "check_this_task" %}
                {% comment %} Check this task {% endcomment %}
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>{% translate "no_tasks_to_check" %}.</p>
    {% comment %} <p>No available tasks for checking.</p> {% endcomment %}
  {% endif %}

  <h2>{% translate "completed_checks" %}</h2>
  {% comment %} <h2>Completed Checks</h2> {% endcomment %}
  {% if checks %}
    <table>
      <thead>
        <tr>
          <th>{% translate "Client" %}</th>
          {% comment %} <th>Task</th> {% endcomment %}
          <th>{% translate "Task" %}</th>
          {% comment %} <th>Task</th> {% endcomment %}
          <th>{% translate "AI_score" %}</th>
          {% comment %} <th>AI Score</th> {% endcomment %}
          <th>{% translate "Status" %}</th>
          {% comment %} <th>Status</th> {% endcomment %}
          <th>{% translate "created_at" %}</th>
          {% comment %} <th>Created</th> {% endcomment %}
        </tr>
      </thead>
      <tbody>
        {% for check in checks %}
          <tr>
            <td>{{ check.task.client.username }}</td>
            <td>
              <a href="{% url 'tasks:text-check-perform' check.task.id %}">{{ check.task.title }}</a>
            </td>
            <td>{{ check.ai_score }}%</td>
            <td>{{ check.get_status_display }}</td>
            <td>{{ check.updated_at|date:"d.m.Y H:i" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>{% translate "no_checks_made" %}.</p>
    {% comment %} <p>You haven't checked any tasks yet.</p> {% endcomment %}
  {% endif %}
{% endblock content %}

django_project/templates/tasks/my_text_tasks.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% translate "my_text_tasks" %}
{% endblock title %}

{% block content %}
  <h1>{% translate "my_text_tasks" %}</h1>
  {% comment %} <h1>My Tasks</h1> {% endcomment %}
  <a href="{% url 'tasks:text-task-create' %}">{% translate "create_text_task" %}</a>
  {% if tasks %}
    <table>
      <thead>
        <tr>
          <th>{% translate "Title" %}</th>
          {% comment %} <th>Title</th> {% endcomment %}
          <th>{% translate "created_at" %}</th>
          {% comment %} <th>Created</th> {% endcomment %}
          <th>{% translate "AI_score" %}</th>
          {% comment %} <th>AI Score</th> {% endcomment %}
          <th>{% translate "checks_count" %}</th>
          {% comment %} <th>Checks Count</th> {% endcomment %}
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
          <tr>
            <td>
              <a href="{% url 'tasks:text-task-detail' task.id %}">{{ task.title }}</a>
            </td>
            <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
            <td>
              {% if task.ai_score %}
                {{ task.ai_score|floatformat:1 }}%
              {% else %}
                {% translate "not_checked" %}
                {% comment %} Not checked {% endcomment %}
              {% endif %}
            </td>
            <td>{{ task.checks_count }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>{% translate "no_text_tasks_made" %}.</p>
    {% comment %} <p>You have no tasks yet</p> {% endcomment %}
  {% endif %}
{% endblock content %}

django_project/templates/tasks/task_create.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block extra_head %}
  {{ form.media }}
{% endblock extra_head %}
{% block title %}
  {% translate "Create_task" %}
{% endblock title %}

{% block head %}
  {% translate "Create_task" %}
{% endblock head %}

{% block col-card-md %}
  11
{% endblock col-card-md %}

{% block form_fields %}
  {% for field in form %}
    {% if forloop.first %}
      <div class="form-floating mx-auto col-11 col-md-5">
        {{ field }}
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
          {% if field.field.required %}<span>*</span>{% endif %}
        </label>
      </div>
    {% elif forloop.last %}
      {% if field.field.widget.input_type == "file" %}
        <div class="form-floating mx-auto col-11 col-md-5">
          <div>{{ field }}</div>
        </div>
      {% else %}
        <div class="form-floating mt-4 mx-auto col-11 col-md-10 roboto">{{ field }}</div>
      {% endif %}
    {% else %}
      <div class="form-floating mx-auto col-11 col-md-5">
        {{ field }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      </div>
    {% endif %}
  {% endfor %}

{% endblock form_fields %}

{% block buttons %}
  <div class="d-flex flex-column gap-2 mt-3 align-items-center justify-content-center ">
    <button type="submit" class="btn btn-primary btn-lg">{% translate "Create" %}</button>
  </div>
{% endblock buttons %}

django_project/templates/tasks/taskcheck_create.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <div class="container">
    <h2>{% translate "Check_of_task" %}: {{ task.title }}</h2>
    {% comment %} Check of task: {% endcomment %}

    <div class="alert alert-info">
      <p>
        <strong>{% translate "text_of_task" %}:</strong>
      </p>
      {% comment %} <p><strong>Text of task:</strong></p> {% endcomment %}
      <div class="text-content p-2 bg-light border">{{ task.content|linebreaks }}</div>
    </div>

    <form method="post">
      {% csrf_token %}
      {{ form.media }}
      {{ form.as_p }}
      <hr>
      {% if form.instance.status == 'published' %}
        <div class="alert alert-success">
          {% translate "Check_already_published" %}
          {% comment %} ✅ You've already sent the result to the client. Changes are not possible. {% endcomment %}
        </div>
        <a href="{% url 'homepage:index' %}" class="btn btn-secondary">{% translate "Return" %}</a>
        {% comment %} <a href="{% url 'homepage:index' %}" class="btn btn-secondary">Return</a> {% endcomment %}
      {% else %}
        <div class="d-flex gap-2">
          <button type="submit" name="action" value="save_draft" class="btn btn-secondary">
            {% translate "Save_draft" %}
            {% comment %} Save draft {% endcomment %}
          </button>

          <button type="submit" name="action" value="publish" class="btn btn-primary" onclick="return confirm('Вы уверены? После отправки изменить вердикт будет нельзя.');">
            {% translate "Send_check" %}
            {% comment %} Send check {% endcomment %}
          </button>
        </div>
      {% endif %}
    </form>
  </div>
{% endblock content %}

django_project/templates/tasks/text_task_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  <title>{{ task.title }}</title>
{% endblock title %}

{% block content %}
  <h1>{{ task.title }}</h1>

  <div class="task-info">
    {% translate "task_information" %}
    {% comment %} <h2>Task Information</h2> {% endcomment %}
    <p>
      <strong>{% translate "created_at" %}:</strong>
      {{ task.created_at|date:"d.m.Y H:i" }}
    </p>
    {% comment %} <p><strong>Created:</strong> {{ task.created_at|date:"d.m.Y H:i" }}</p> {% endcomment %}
    {% if task.description %}
      <p>
        <strong>{% translate "Description" %}:</strong> {{ task.description }}
      </p>
      {% comment %} <p><strong>Description:</strong> {{ task.description }}</p> {% endcomment %}
    {% endif %}

    <p>
      <strong>{% translate "Content" %}:</strong>
    </p>
    {% comment %} <p><strong>Content:</strong></p> {% endcomment %}
    <div class="content-box">{{ task.content|linebreaks }}</div>

    <p>
      <strong>{% translate "AI_score" %}:</strong>
      {% comment %} <strong>AI Score:</strong> {% endcomment %}
      {% if task.ai_score %}
        {{ task.ai_score|floatformat:1 }}%
      {% else %}
        {% translate "not_evaluated" %}
        {% comment %} Not evaluated yet {% endcomment %}
      {% endif %}
    </p>

    <p>
      <strong>{% translate "total_checks" %}:</strong> {{ task.checks_count }}
    </p>
    {% comment %} <p><strong>Total Checks:</strong> {{ checks.count }}</p> {% endcomment %}
  </div>

  <div class="checks-list">
    <h2>{% translate "Checks" %}</h2>
    {% comment %} <h2>Checks</h2> {% endcomment %}

    {% if task.checks.all %}
      <table>
        <thead>
          <tr>
            <th>{% translate "Performer" %}</th>
            {% comment %} <th>Performer</th> {% endcomment %}
            <th>{% translate "AI_score" %}</th>
            {% comment %} <th>AI Score</th> {% endcomment %}
            <th>{% translate "Comment" %}</th>
            {% comment %} <th>Comment</th> {% endcomment %}
            <th>{% translate "published_at" %}</th>
            {% comment %} <th>Created</th> {% endcomment %}
          </tr>
        </thead>
        <tbody>
          {% for check in task.checks.all %}
            <tr>
              <td>{{ check.performer.username }}</td>
              <td>{{ check.ai_score }}%</td>
              <td>
                {% if check.comment %}
                  {{ check.comment|truncatechars:100 }}
                {% else %}
                  {% translate "no_comment" %}
                  {% comment %} No comment {% endcomment %}
                {% endif %}
              </td>
              <td>{{ check.updated_at|date:"d.m.Y H:i" }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>{% translate "No_checks_yet" %}.</p>
      {% comment %} <p>No checks yet.</p> {% endcomment %}
    {% endif %}
  </div>

  <a href="{% url 'tasks:my-text-tasks' %}">{% translate "Back_to_my_tasks" %}</a>
  {% comment %} <a href="{% url 'tasks:my-text-tasks' %}">Back to My Tasks</a> {% endcomment %}
{% endblock content %}

django_project/templates/tasks/texttask_create.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% translate "Create_task" %}
  {% comment %} Create task {% endcomment %}
{% endblock title %}

{% block content %}
  <h1>{% translate Create_new_task %}</h1>
  {% comment %} <h1>Create new task</h1> {% endcomment %}

  {% if messages %}
    {% for message in messages %}<p>{{ message }}</p>{% endfor %}
  {% endif %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% translate "Create_task" %}</button>
    {% comment %} <button type="submit">Create task</button> {% endcomment %}
  </form>
{% endblock content %}